# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 23:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_submission_sumission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='sumission',
            new_name='submission',
        ),
    ]
