# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_auto_20171120_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='total_points',
        ),
        migrations.AlterField(
            model_name='submission',
            name='points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
