# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_auto_20171122_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='total_points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
