# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20171127_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='syllabus',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
