# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='question',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
