# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 19:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_assignment_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='points',
            new_name='total_points',
        ),
    ]
