# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_auto_20171130_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='title',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
