# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_course_user'),
        ('accounts', '0002_auto_20171104_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(blank=True, to='courses.Course'),
        ),
    ]
