# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
